defaults:
  - _self_
  - env: shadow_hand
  - override hydra/launcher: local
  - override hydra/output: local

hydra:
  job:
    chdir: True

paths:
  project_root: null
  isaac_root: ${paths.project_root}/../isaacgymenvs/isaacgymenvs

# LLM parameters
model: gpt-4-0314  # LLM model (other options are gpt-4, gpt-4-0613, gpt-3.5-turbo-16k-0613)
temperature: 1.0
suffix: GPT  # suffix for generated files (indicates LLM model)
api_key: null  # API key for LLM
base_url: null  # base URL for LLM API

# EurekaPlus parameters
enable_module_pool: False  # whether to enable module pool for function generation
iteration: 1  # how many iterations of EurekaPlus to run
sample: 3  # number of function candidates to generate per iteration
max_iterations: 3000  # RL Policy training iterations (decrease this to make the feedback loop faster)
num_eval: 5  # number of evaluation episodes to run for the final reward
max_eval_iterations: 20000  # max iterations for each independent evaluation run
capture_video: False  # whether to capture policy rollout videos

# Weights and Biases
use_wandb: False  # whether to use wandb for logging
wandb_username: ""  # wandb username if logging with wandb
wandb_project: ""  # wandb project if logging with wandb